name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: "Build"
        run: |
          docker build --tag pg . && docker create --name pg pg ignored && docker cp pg:/psql-static .

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            psql-static
